name: ForceDismount
main: com.creeperevents.plugin.ForceDismount
version: 1.0
description: Make a player dismount a vehicle
author: oggehej
commands:
  dismount:
    description: Make a player dismount a vehicle
    usage: /<command> <player>
    permission: forcedismount.use
permissions:
  forcedismount.use:
    description: Allows to make players dismount their vehicles
    default: op
  forcedismount.exempt:
    description: Player can't be forced to dismount a vehicle
    default: false
